export const joblist = [
  {
    type: "planners",
    label: "Planners",
    group: "master",
    options: ["Net", "Target"],
    option: "Net",
  },
  {
    type: "currency",
    label: "Currency",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "uom",
    label: "UOM",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "calendar",
    label: "Calendar",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "orgs",
    label: "Organizations",
    group: "master",
    options: ["Net", "Target"],
    option: "Net",
  },
  {
    type: "locations",
    label: "Locations",
    group: "master",
    options: ["Net", "Target"],
    option: "Net",
  },
  {
    type: "customers",
    label: "Customers",
    group: "master",
    options: ["Net", "Target"],
    option: "Net",
  },
  {
    type: "items",
    label: "Items",
    group: "master",
    options: ["Net", "Target"],
    option: "Net",
  },
  {
    type: "demandCls",
    label: "Demand Class",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "catalogs",
    label: "Catalogs",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "udHierarchy",
    label: "User Defined Hierarchy",
    group: "master",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "sOrder",
    label: "Sales Order",
    group: "transactional",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "bookHistory",
    label: "Booking History",
    group: "transactional",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "shipHistory",
    label: "Shipping History",
    group: "transactional",
    options: ["Target"],
    option: "Target",
  },
  {
    type: "forecast",
    label: "Demand Planning Forecast",
    group: "transactional",
    options: ["Target"],
    option: "Target",
  },
];
